twig:
  default_path: "%kernel.project_dir%/templates"
  form_themes: ["bootstrap_5_layout.html.twig"]
  globals:
    name: "Steven Sinprasith"
    address: "rue chateaubriand 91600 savigny sur orge"
    email: "sinprasith.steven@3wa.io"
    company: "Samleak"
    telephone: "0669264517"
    siret: "832189021020456"
    ape: "6201Z"
    currency: "€"
    tva: "Non applicable ART.293B du CGI"
    quantity: "1"
    host: "ionos"
    domain: "Samleak.fr"
when@test:
  twig:
    strict_variables: true
