twig:
  default_path: "%kernel.project_dir%/templates"
  form_themes: ["bootstrap_5_layout.html.twig"]
  globals:
    name: "Perez Geoffrey"
    address: "39 rue Jean-Baptiste Martini 83500 La Seyne-sur-mer"
    email: "geoffrey.perez@3wa.io"
    company: "AtlierPanthera"
    telephone: "0625535186"
    siret: "83218902100021"
    ape: "6201Z"
    currency: "€"
    tva: "Non applicable ART.293B du CGI"
    quantity: "1"
    host: "ionos"
    domain: "atelierpanthera.fr"
when@test:
  twig:
    strict_variables: true
