name: Test Symfony Build Only

on:
  workflow_dispatch:  # Permet de le lancer manuellement depuis GitHub
  push:
    branches:
      - main  # Tu peux changer la branche si besoin

jobs:
  test-symfony-build:
    name: Build Symfony + Webpack (no deploy)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Node modules and build assets
        run: |
          npm ci
          npm run build

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo, pdo_mysql
          tools: composer

      - name: Create .env file from secrets
        run: |
          echo "APP_ENV=prod" >> .env
          echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "MAILER_DSN=${{ secrets.MAILER_DSN }}" >> .env
          echo "ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}" >> .env
          echo "STRIPE_SECRET_KEY_DEV=${{ secrets.STRIPE_SECRET_KEY_DEV }}" >> .env
          echo "STRIPE_SECRET_KEY_PROD=${{ secrets.STRIPE_SECRET_KEY_PROD }}" >> .env

      - name: Composer install + cache clear
        run: |
          composer install --no-dev --optimize-autoloader
          php bin/console cache:clear --no-warmup --no-debug